var arrLang = {
  en: {
    home: "Home",
    discount: "Complexes",
    infoAndRules: "Info&Rules",
    appointment: "Make an appointment",
    ourPrice: "Our Price",
    forWoman: "For Woman",
    forMan: "For Man",
    head: "Head",
    oneAreaFace: "One area of the face",
    faceCompletely: "The face is completely",
    neck: "Neck front and back",
    hands: "Hands",
    armsUpElbow: "Arms up to the elbow",
    handsAboveElbow: "Hands above the elbow",
    handsCompletely: "Hands Completely",
    armpits: "Armpits",
    torsoFront: "Torso front",
    areoles: "Areoles",
    bellyCompletely: "The belly is completely",
    bellyLine: "Belly line",
    chestCompletely: "The chest is completely",
    torsoBack: "Torso back",
    lowerBack: "Lower back",
    backCompletely: "The back is completely",
    legs: "Legs",
    hips: "Hips",
    shinsAndKnees: "Shins and knees",
    legsCompletely: "Legs completely",
    footLift: "Foot lift",
    other: "Other",
    toes: "Toes",
    fingersHands: "Fingers on the hands",
    deepBikini: "Deep bikini",
    bikiniClassics: "Bikini classics",
    buttocks: "Buttocks",
    footerPhone: "Phone: 123 1231 123",
  },
  rs: {
    home: "Kuća",
    discount: "Kompleksi",
    infoAndRules: "Informacije",
    appointment: "Zakazati sastanak",
    ourPrice: "Naše Cene",
    forWoman: "Za žene",
    forMan: "Za muškarce",
    head: "Glava",
    oneAreaFace: "Jedna oblast na licu",
    faceCompletely: "Lice je potpuno",
    neck: "Vrat napred i pozadi",
    hands: "Ruke",
    armsUpElbow: "Ruke do lakta",
    handsAboveElbow: "Ruke iznad lakta",
    handsCompletely: "Cele ruke",
    armpits: "Pazusi",
    torsoFront: "Torzo, prednja strana",
    areoles: "Bradavice",
    bellyCompletely: "Ceo stomak",
    bellyLine: "Deo stomaka",
    chestCompletely: "Prsa",
    torsoBack: "Torzo, pozadi ",
    lowerBack: "Donji deo leđa",
    backCompletely: "Cela leđa",
    legs: "Noge",
    hips: "Bedra",
    shinsAndKnees: "Kolena i potkolenice",
    legsCompletely: "Cele noge",
    footLift: "Gornji deo stopala",
    other: "Drugi",
    toes: "Prsti na nogama",
    fingersHands: "Prsti na rukama",
    deepBikini: "Brazilska epilacija",
    bikiniClassics: "Intimna zona (1)",
    buttocks: "Intimna zona (2)",
    footerPhone: "Telefon: 123 1231 123",
  },
  ru: {
    home: "Домой",
    discount: "Комплексы",
    infoAndRules: "Информация",
    appointment: "Записаться",
    ourPrice: "Наши Цены",
    forWoman: "Для Женщин",
    forMan: "Для Мужчин",
    head: "Голова",
    oneAreaFace: "Одна зона на лице",
    faceCompletely: "Лицо полностью",
    neck: "Шея спереди и сзади",
    hands: "Руки",
    armsUpElbow: "Руки до локтя",
    handsAboveElbow: "Руки выше локтя",
    handsCompletely: "Руки полностью",
    armpits: "Подмышечные впадины",
    torsoFront: "Торс, фронтальная сторона",
    areoles: "Ареолы",
    bellyCompletely: "Живот полностью",
    bellyLine: "Линия живота",
    chestCompletely: "Грудь полностью",
    torsoBack: "Торс, тыловая сторона",
    lowerBack: "Поясница",
    backCompletely: "Спина полностью",
    legs: "Ноги",
    hips: "Бедра",
    shinsAndKnees: "Голени с коленями",
    legsCompletely: "Ноги полностью",
    footLift: "Подъем стопы",
    other: "Другое",
    toes: "Пальцы ног",
    fingersHands: "Пальцы рук",
    deepBikini: "Глубокое бикини",
    bikiniClassics: "Бикини классика",
    buttocks: "Ягодицы",
    footerPhone: "Телефон: 123 1231 123",
  },
};

$(function () {
  $(".translate").click(function () {
    var lang = $(this).attr("id");

    $(".lang").each(function (index, item) {
      $(this).text(arrLang[lang][$(this).attr("key")]);
    });
  });
});
